name: Build and Test
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

runs:
  using: composite
  steps:
    - name: Setup .NET 9
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore Dependencies
      shell: bash
      run: dotnet restore

    - name: Build
      shell: bash
      run: dotnet build --configuration Release p:Version=${{ inputs.version }} /p:FileVersion=${{ inputs.version }}

    - name: Test
      shell: bash
      run: dotnet test --configuration Release --logger "trx;LogFileName=test-results.trx" --results-directory "TestResults" --collect:"XPlat Code Coverage"
