name: Publish toNuGet
on:
  push:
    tags:
      - "*.*.*"

env:
  NUGET_PACKAGE_DIR: ./nupkg
  NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
  NUGET_SOURCE: ${{ vars.NUGET_SOURCE }}

jobs:
  Publish:
    if: github.event.base_ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build and Test
        uses: ./.github/actions/build-and-test

      - name: Create Package
        run: dotnet pack --configuration Release --no-build --output $NUGET_PACKAGE_DIR /p:Version=${{ github.ref_name }} /p:PackageVersion=${{ github.ref_name }}

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Cake.GoogleTest
          path: ${{ env.NUGET_PACKAGE_DIR }}/*.nupkg

      # - name: Publish to Nuget
      #   run: dotnet nuget push $NUGET_PACKAGE_DIR/*.nupkg --api-key $NUGET_API_KEY --source $NUGET_SOURCE
